services:
  - type: web
    name: gestion-courses
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node backend/index.js
    envVars:
      - key: NODE_ENV
        value: production